version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka_exporter:
    image: danielqsj/kafka-exporter:v1.4.2
    restart: on-failure
    command:
      - --kafka.version=3.0.0
    ports:
      - "9308:9308"

  prometheus:
    image: prom/prometheus:v2.31.1
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:8.2.5
    ports:
      - "3000:3000"